name: Cypress Smoke Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - postsync_hook

jobs:
  gateway:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@merlot-education'
          token: ${{ secrets.PACKAGES_RW_TOKEN }}

      - run: npm ci

      - name: Run full test suite
        uses: cypress-io/github-action@v5.5.1
        with:
          build: npm run build
          start: npm run qa
          config: baseUrl=https://marketplace.dev.merlot-education.eu
